version: '3'
services:
  database:
    image: "mongo:latest"
    restart: always
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://database:27018

  frontend:
    build:
      context: ./Site
      dockerfile: Dockerfile
    restart: always
    environment:
      - BASE_URL=/api
      - NODE_ENV=production

  caddy:
    image: "caddy:latest"
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /path/to/your/ssl/certificates:/etc/caddy/certs
    ports:
      - "80:80"
      - "443:443"

volumes:
  mongodb_data:
