version: '3'
services:
    backend:
      image: node:18-alpine
      command: yarn start
      working_dir: /app
      volumes:
        - ./server:/app
      ports:
        - "8000:8000"
 

    database:
      image: "mongo:latest"
      volumes:
        - mongodb_data:/data/db
      ports:
        - "27017:27017"


    frontend:
      image: "node:18-alpine"
      environment:
        - HOST=0.0.0.0
      working_dir: /app
      volumes:
        - ./Site:/app
      command: yarn dev
      ports:
        - "3000:3000"
 

volumes:
  mongodb_data:

# version: '3'
# services:
#   backend:
#     image: node:18-alpine
#     command: yarn start
#     working_dir: /app
#     volumes:
#       - ./server:/app
#     ports:
#       - "8000:8000"

#   database:
#     image: "mongo:latest"
#     command: mongod --bind_ip_all
#     ports:
#       - "27017:27017"

#   frontend:
#     image: "node:18-alpine"
#     environment:
#       - HOST=0.0.0.0
#     working_dir: /app
#     volumes:
#       - ./Site:/app
#     command: yarn dev
#     ports:
#       - "3000:3000"

# # mongod.conf

# # for documentation of all options, see:
# #   http://docs.mongodb.org/manual/reference/configuration-options/

# # Where and how to store data.
# storage:
#   dbPath: /var/lib/mongodb
# #  engine:
# #  wiredTiger:

# # where to write logging data.
# systemLog:
#   destination: file
#   logAppend: true
#   path: /var/log/mongodb/mongod.log

# # network interfaces
# net:
#   port: 27017
#   bindIp: 0.0.0.0


# # how the process runs
# processManagement:
#   timeZoneInfo: /usr/share/zoneinfo

# #security:

# #operationProfiling:

# #replication:

# #sharding:

# ## Enterprise-Only Options: