version: '3'
services:
    backend:
      image: node:18-alpine
      command: yarn start
      working_dir: /app
      volumes:
        - ./server:/app
      ports:
        - "8000:8000"
 

    database:
      image: "mongo:latest"
      # volumes:
      #   - mongodb_data:/data/db
      ports:
        - "27017:27018"


    frontend:
      image: "node:18-alpine"
      environment:
        - HOST=0.0.0.0
      working_dir: /app
      volumes:
        - ./Site:/app
      command: yarn dev
      ports:
        - "3000:3000"
 

volumes:
  mongodb_data:


